# Site settings
title: Applied Optics research at Universidad Nacional de Colombia
lab_name: Applied Optics Laboratoty
author: >
  The applied optics group
institution: Universidad Nacional de Colombia
email: oeolartep@unal.edu.co
description: >
  The Applied Optics Lab is devoted to the advancement of optical sciences focused on applications, from visual sciences and biomedical imaging to industrial holography. 
baseurl: ""
url: "https://appliedopticsun.github.io"
twitter_username: none
github_username:  appliedopticsun
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
