# Site settings
lab_name: John Doe Lab
institution: Science University
email: john.doe@example.com
description: >
  This research lab specializes in science and makes
  novel discoveries with translational impact.
baseurl: ""
url: "http://johndoelab.github.io"
twitter_username: johndoelab
github_username:  johndoelab

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/
gems:
    - jekyll-redirect-from
