# Site settings
lab_name: Bruno Grande Lab
institution: Science University
email: bgrande@sfu.ca
description: >
  This research lab specializes in science and makes
  novel discoveries with translational impact.
baseurl: "/guild"
url: "http://bgran.de/guild"
twitter_username: grandebruno
github_username:  brunogrande
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/
